services:
  flights:
    build:
      context: .
      dockerfile: ./apps/flights/Dockerfile
      target: development
    command: pnpm run start:dev flights
    container_name: flights
    env_file:
      - ./apps/flights/.env
    ports:
      - '5001:5001'
    volumes:
      - .:/usr/src/app
    networks:
      - kafka-network

  hotels:
    build:
      context: .
      dockerfile: ./apps/hotels/Dockerfile
      target: development
    command: pnpm run start:dev hotels
    container_name: hotels
    env_file:
      - ./apps/hotels/.env
    ports:
      - '5002:5002'
    volumes:
      - .:/usr/src/app
    networks:
      - kafka-network

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    container_name: payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/usr/src/app
    networks:
      - kafka-network

  saga:
    build:
      context: .
      dockerfile: ./apps/saga/Dockerfile
      target: development
    command: pnpm run start:dev saga
    container_name: saga
    env_file:
      - ./apps/saga/.env
    volumes:
      - .:/usr/src/app
    networks:
      - kafka-network


  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "9005:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge